spring.application.name=myvet

# Configuracao do banco MySQL
spring.datasource.url=${URL_BANCO}
spring.datasource.username=${USERNAME_BANCO}
spring.datasource.password=${PASSWORD_BANCO}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Configuracoes de exibicao de SQL no console
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

