spring.application.name=myvet

# Configuracao do banco MySQL
# spring.datasource.url=${URL_BANCO}
# spring.datasource.username=${USERNAME_BANCO}
# spring.datasource.password=${PASSWORD_BANCO}
# spring.datasource.url=jdbc:postgresql://localhost:5432/myvet
# spring.datasource.username=postgres
# spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://ep-fancy-sea-accupwzc-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_E13kfCoTytAQ
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracao do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Configuracoes de exibicao de SQL no console
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

